// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMoNWeAm4ciECe6EXovguKbLpYe0LX6BA',
    appId: '1:140095783650:web:9c51c11cbe2001ce7114bb',
    messagingSenderId: '140095783650',
    projectId: 'chatapp-33de0',
    authDomain: 'chatapp-33de0.firebaseapp.com',
    storageBucket: 'chatapp-33de0.appspot.com',
    measurementId: 'G-T498FZBZ1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaapRyQNhk1Y0XrnHY3ZTHYZL-GaYXvsI',
    appId: '1:140095783650:android:70af1b129b8a730c7114bb',
    messagingSenderId: '140095783650',
    projectId: 'chatapp-33de0',
    storageBucket: 'chatapp-33de0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA2poxau94_1VkiOH0nMyCLDD0NW4YNNM',
    appId: '1:140095783650:ios:6f0ff2e46f60e8b67114bb',
    messagingSenderId: '140095783650',
    projectId: 'chatapp-33de0',
    storageBucket: 'chatapp-33de0.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA2poxau94_1VkiOH0nMyCLDD0NW4YNNM',
    appId: '1:140095783650:ios:b951ef7281fd115f7114bb',
    messagingSenderId: '140095783650',
    projectId: 'chatapp-33de0',
    storageBucket: 'chatapp-33de0.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp.RunnerTests',
  );
}
